In [ ]:
import numpy as np

# 1. Создание массивов разными способами
a = np.array([[1, 2, 3], [4, 5, 6]])          # из списка
b = np.zeros((2, 4))                          # нули
c = np.ones((3, 3))                           # единицы
d = np.arange(12).reshape(3, 4)               # arange + reshape

print("Массив d:")
print(d)
print("shape:", d.shape)
print("dtype:", d.dtype)

# 2. Индексирование и срезы
print("\nЭлемент [0, 2]:", d[0, 2])
print("Вторая строка:", d[1])
print("Последний столбец:", d[:, -1])
print("Подмассив 2×2 сверху слева:\n", d[:2, :2])

# 3. Векторные операции и статистики
print("\nд + 10:\n", d + 10)
print("д * 2:\n", d * 2)
print("Среднее по массиву:", d.mean())
print("Сумма по столбцам:", d.sum(axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
int64
